const TYPES = {
    EDIT_DESCRIPTION: "EDIT_DESCRIPTION",
    EDIT_IMAGE: "EDIT_IMAGE",
    EDIT_HOJA: "EDIT_HOJA",
    ADD_SKILL: "ADD_SKILL",
    ADD_JOB: "ADD_JOB",
    DELETE_SKILL: "DELETE_SKILL",
    DELETE_JOB: "DELETE_JOB",
};

export default TYPES;